## @file
# Message file to hold the power information
#
# @var float32 voltage
# @var float32 current0
# @var float32 current1
# @var float32 current2
# @var float32 current3
# @var float32 current4
# @var float32 current5
# @var float32 current6
# @var float32 current7
# @var float32 current8
# @var float32 current9
# @var float32 current10
# @var float32 current11
# @var float32 current12
# @var float32 current13
# @var float32 current14
# @var float32 current15

float32 voltage
float32 current0
float32 current1
float32 current2
float32 current3
float32 current4
float32 current5
float32 current6
float32 current7
float32 current8
float32 current9
float32 current10
float32 current11
float32 current12
float32 current13
float32 current14 
float32 current15
