## @file
# Message file to hold the information from the Talon
#
# @var int32 device_id
# @var float32 bus_voltage
# @var float32 output_current
# @var float32 output_voltage
# @var float32 output_percent
# @var float32 temperature
# @var int32 sensor_position
# @var int32 sensor_velocity
# @var int32 closed_loop_error
# @var int32 integral_accumulator
# @var int32 error_derivative

int32 device_id
float32 bus_voltage
float32 output_current
float32 output_voltage
float32 output_percent
float32 temperature
int32 sensor_position
int32 sensor_velocity
int32 closed_loop_error 
int32 integral_accumulator
int32 error_derivative
